package br.com.apoia.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MentorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMentorAllPropertiesEquals(Mentor expected, Mentor actual) {
        assertMentorAutoGeneratedPropertiesEquals(expected, actual);
        assertMentorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMentorAllUpdatablePropertiesEquals(Mentor expected, Mentor actual) {
        assertMentorUpdatableFieldsEquals(expected, actual);
        assertMentorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMentorAutoGeneratedPropertiesEquals(Mentor expected, Mentor actual) {
        assertThat(expected)
            .as("Verify Mentor auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMentorUpdatableFieldsEquals(Mentor expected, Mentor actual) {
        assertThat(expected)
            .as("Verify Mentor relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMentorUpdatableRelationshipsEquals(Mentor expected, Mentor actual) {
        assertThat(expected)
            .as("Verify Mentor relationships")
            .satisfies(e -> assertThat(e.getAreas()).as("check areas").isEqualTo(actual.getAreas()));
    }
}
